# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(746, 368)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)

        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(24)

        self.LA = QtWidgets.QLabel(self.centralwidget)
        self.LA.setFont(font)
        self.LA.setText("Введите число: ")
        self.LA.setGeometry(10, 10, 301, 101)

        self.LB = QtWidgets.QLabel(self.centralwidget)
        self.LB.setFont(font)
        self.LB.setText("Делители: ")
        self.LB.setGeometry(30, 220, 221, 101)


        self.LEa = QtWidgets.QLineEdit(self.centralwidget)
        self.LEa.setFont(font)
        self.LEa.setGeometry(260, 40, 161, 51)

        self.LEb = QtWidgets.QLineEdit(self.centralwidget)
        self.LEb.setFont(font)
        self.LEb.setGeometry(210, 230, 331, 81)
        self.LEb.setReadOnly(True)

        self.LEc = QtWidgets.QLineEdit(self.centralwidget)
        self.LEc.setFont(font)
        self.LEc.setGeometry(20, 120, 321, 81)
        self.LEc.setReadOnly(True)

        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setFont(font)
        self.btn.setText("Определить")
        self.btn.setGeometry(460, 90, 251, 81)
        self.btn.clicked.connect(self.get_dev)
        self.btn.clicked.connect(self.isPrime)





        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


    def isPrime(self):
        x = int(self.LEa.text())
        d = 2
        while d * d <= x and x % d != 0:
            d += 1
        if d ** 2 > x:
            self.LEc.setText("Простое")
        else:
            self.LEc.setText("Непростое")


    def get_dev(self):
        n = int(self.LEa.text())
        i = 1
        a = []
        while i*i <= n:
            if n % i == 0:
                if i == n//i:
                    a.append(i)
                else:
                    a.append(i)
                    a.append(n//i)
            i += 1
        a.sort()

        self.LEb.setText(str(a)[1:-1])









if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
